# Generated by Django 5.2 on 2025-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='product')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
