# Generated by Django 5.2 on 2025-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
